hide_vote_tab_in_navigation:
  default: false
  type: bool
  description: "settings.hide_vote_tab_in_navigation.description"
show_everywhere:
  default: false
  type: bool
  description: "settings.show_everywhere.description"
bells_and_whistles_styling:
  default: false
  type: bool
  description: "settings.bells_and_whistles_styling.description"
hot_votes_minimum:
  default: 5
  type: integer
  description: "settings.hot_votes_minimum.description"
